/* MAX HITRADIO v2 — optional Firebase community modules; no secrets in browser. */
const $ = id => document.getElementById(id);
const CFG = window.MAX_CONFIG || {};
const STREAM = 'https://audio.cloudrad.io/ef465bb5/live';
let fb = null, auth = null, db = null, messaging = null, fn = null, user = null, admin = false;
let current = {artist:'',title:''}, lastTrack = '', localHistory = readLocal('max-history',[]), favorites = readLocal('max-favorites',[]);
let currentEventId='', lastListeners=''; const listenUnsubs=[];
const collectionNames = ['news','top40','djs','programs','events','contests','polls','station'];
const data = Object.fromEntries(collectionNames.map(k=>[k,[]]));
function readLocal(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch{return fallback}}
function saveLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function n(tag,txt,cls){const el=document.createElement(tag);if(txt!==undefined)el.textContent=String(txt);if(cls)el.className=cls;return el}
function clear(node){node.replaceChildren()}
function safeLink(url){try{const x=new URL(url);return x.protocol==='https:'?x.href:null}catch{return null}}
function notice(id,msg){$(id).textContent=msg}
function needsLogin(){if(!fb){showAuth('Online functies zijn nog niet aangesloten. De beheerder moet eerst Firebase configureren.');return false}if(!user){showAuth('Log in om deze functie te gebruiken.');return false}return true}
function dateStr(s){const d=new Date(s);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(d):'Datum nog onbekend'}
function sorted(items,k='order'){return [...items].sort((a,b)=>Number(a[k]??999)-Number(b[k]??999))}
function panelHead(parent,title,sub){parent.append(n('strong',title));if(sub)parent.append(n('p',sub,'muted small'))}
function renderEmpty(container,items,text){clear(container);if(!items.length){container.append(n('p',text,'muted'));return true}return false}
function renderHistory(){const root=$('historyList');clear(root);if(!localHistory.length){root.append(n('li','Zodra een nummer speelt, zie je het hier.'));return}localHistory.slice(0,12).forEach(t=>root.append(n('li',`${t.artist||'MAX HITRADIO'} — ${t.title}`)))}
$('historyClear').addEventListener('click',()=>{localHistory=[];saveLocal('max-history',[]);renderHistory()});
function renderFav(){const root=$('favoritesList');if(renderEmpty(root,favorites,'Nog geen nummers opgeslagen.'))return;favorites.forEach(t=>{const item=n('div',undefined,'listline');item.append(n('span',`${t.artist} — ${t.title}`));const b=n('button','Verwijder','small-btn');b.addEventListener('click',async()=>{favorites=favorites.filter(f=>`${f.artist}|${f.title}`!==`${t.artist}|${t.title}`);saveLocal('max-favorites',favorites);renderFav();await syncFavorites()});item.append(b);root.append(item)})}
async function syncFavorites(){if(!db||!user)return;try{await fb.setDoc(fb.doc(db,'favorites',user.uid),{items:favorites.slice(0,80),updatedAt:fb.serverTimestamp()})}catch(e){notice('playerNote','Favorieten op dit apparaat opgeslagen; online synchronisatie niet beschikbaar.')}}
$('favoriteCurrent').addEventListener('click',async()=>{if(!current.title)return notice('playerNote','Wacht tot CloudRadio een nummer doorgeeft.');const key=t=>`${t.artist}|${t.title}`;if(!favorites.some(x=>key(x)===key(current)))favorites.unshift({...current});favorites=favorites.slice(0,80);saveLocal('max-favorites',favorites);renderFav();notice('playerNote','Opgeslagen bij favorieten');await syncFavorites()});
$('shareCurrent').addEventListener('click',async()=>{const text=current.title?`${current.artist} — ${current.title} op MAX HITRADIO`: 'Luister naar MAX HITRADIO';const url='https://thegamerscube.nl/max/';try{if(navigator.share){await navigator.share({title:'MAX HITRADIO',text,url})}else{await navigator.clipboard.writeText(`${text} ${url}`);notice('playerNote','Link en nummer gekopieerd!')}}catch(e){if(e.name!=='AbortError')notice('playerNote','Delen niet beschikbaar in deze browser.')}});
$('artistLookup').addEventListener('click',async()=>{if(!current.artist)return notice('artistInfo','Artiest nog niet bekend.');notice('artistInfo',`Informatie ophalen over ${current.artist}…`);$('artistSource').hidden=true;try{const artist=current.artist.replace(/\s+(feat\.?|ft\.?|&).*$/i,'').trim();const u=new URL('https://nl.wikipedia.org/w/api.php');u.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:artist,gsrlimit:'4',prop:'extracts',exintro:'1',explaintext:'1',exsentences:'3',format:'json',origin:'*'}).toString();const r=await fetch(u);if(!r.ok)throw Error();const j=await r.json();const arr=Object.values(j.query?.pages||{});const v=arr.find(x=>x.title.toLowerCase()===artist.toLowerCase())||arr.find(x=>x.extract?.toLowerCase().includes(artist.toLowerCase()))||arr[0];if(!v?.extract)throw Error();notice('artistInfo',v.extract.slice(0,700));const link=`https://nl.wikipedia.org/wiki/${encodeURIComponent(v.title.replaceAll(' ','_'))}`;$('artistSource').href=link;$('artistSource').hidden=false}catch{notice('artistInfo',`Geen geverifieerde informatie gevonden. Zoek op Wikipedia naar ${current.artist}.`);$('artistSource').href=`https://nl.wikipedia.org/w/index.php?search=${encodeURIComponent(current.artist)}`;$('artistSource').textContent='Zoek op Wikipedia ↗';$('artistSource').hidden=false}});
function parseSong(str){if(!str)return null;let raw=str.trim();if(!raw||/^(loading|laden|onbekend|unknown|[-–—])$/i.test(raw))return null;const i=raw.indexOf(' - ');return i>-1?{artist:raw.slice(0,i).trim(),title:raw.slice(i+3).trim()}:{artist:'',title:raw}}
function updateCloud(){const source=$('stream_info_song');const t=parseSong(source.textContent||'');if(t&&t.title){const key=t.artist+'|'+t.title;current=t;$('miniTrack').textContent=(t.artist?t.artist+' — ':'')+t.title;if(key!==lastTrack){lastTrack=key;localHistory=localHistory.filter(h=>h.artist+'|'+h.title!==key);localHistory.unshift({...t,at:new Date().toISOString()});localHistory=localHistory.slice(0,12);saveLocal('max-history',localHistory);renderHistory()}}const raw=($('stream_info_listeners').textContent||'').trim();if(/^\d+$/.test(raw)&&raw!==lastListeners){lastListeners=raw;notice('listenerCount',`${raw} luisteraars volgens CloudRadio`);notice('adminStats',`Actueel CloudRadio-luisteraantal: ${raw}. Dit is geen historische statistiek.`)}}
new MutationObserver(updateCloud).observe($('stream_info_song'),{childList:true,characterData:true,subtree:true});new MutationObserver(updateCloud).observe($('stream_info_listeners'),{childList:true,characterData:true,subtree:true});updateCloud();renderHistory();renderFav();
$('miniPlay').addEventListener('click',()=>$('play').click());const aud=$('audio');aud.addEventListener('play',()=>$('miniPlay').textContent='Ⅱ');aud.addEventListener('pause',()=>$('miniPlay').textContent='▶');
function renderTop(){const root=$('topList');let items=sorted(data.top40.filter(x=>x.published===true),'rank').slice(0,40);if(renderEmpty(root,items,'De Top 40 is nog niet gepubliceerd.'))return;items.forEach(i=>{const li=n('li',undefined,'rank');li.append(n('b',String(i.rank||'–')));li.append(n('span',`${i.artist||''} — ${i.title||''}`));root.append(li)})}
function renderDjs(){const root=$('djList'),items=data.djs.filter(x=>x.published===true);if(renderEmpty(root,items,"DJ-profielen verschijnen zodra ze definitief zijn."))return;items.forEach(x=>{let el=n('article',undefined,'mini-card');let img=safeLink(x.image);if(img){const im=document.createElement('img');im.src=img;im.alt=x.name||'DJ';im.loading='lazy';el.append(im)}panelHead(el,x.name||'MAX DJ',x.bio||'');root.append(el)})}
function renderSchedule(){const r=$('scheduleList'),items=sorted(data.programs.filter(x=>x.published===true),'sort');if(renderEmpty(r,items,'De programmering is nog in voorbereiding.'))return;items.forEach(x=>{let e=n('div',undefined,'listline');let left=n('div');panelHead(left,x.title||'Programma',`${x.day||''} ${x.start||''}–${x.end||''}${x.dj?' · '+x.dj:''}`);e.append(left);r.append(e)});let show=(data.station.find(x=>x.id==='current')||{});notice('onAirProgram',show.program?`Nu: ${show.program}${show.dj?' met '+show.dj:''}`:'Bekijk hieronder de gepubliceerde programma’s. De live-DJ wordt later ingesteld.')}
function renderEvents(){const r=$('eventList'),items=data.events.filter(x=>x.published===true).sort((a,b)=>new Date(a.date)-new Date(b.date));if(renderEmpty(r,items,'Nog geen speciale uitzendingen aangekondigd.'))return;items.forEach(x=>{let e=n('article',undefined,'mini-card');panelHead(e,x.title||'Speciale uitzending',x.description||'');e.append(n('p',dateStr(x.date),'accent'));const timer=n('strong','Aftellen…','countdown');e.append(timer);function tick(){if(!timer.isConnected)return;let diff=new Date(x.date)-Date.now();if(!Number.isFinite(diff)){timer.textContent='Datum wordt bekendgemaakt';return}if(diff<=0){timer.textContent='Tijdstip bereikt';return}const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000);timer.textContent=`${d} dagen · ${h} uur · ${m} min`};tick();const ti=setInterval(()=>{if(!timer.isConnected){clearInterval(ti);return}tick()},60000);r.append(e)})}
function renderNews(){let root=$('newsList'),items=data.news.filter(x=>x.published===true).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));if(renderEmpty(root,items,'Nog geen nieuwsberichten gepubliceerd.'))return;items.forEach(x=>{const el=n('article',undefined,'mini-card');el.append(n('span',dateStr(x.date),'accent small'));panelHead(el,x.title||'MAX Nieuws',x.body||'');const link=safeLink(x.url);if(link){const a=n('a','Meer informatie ↗');a.href=link;a.target='_blank';a.rel='noopener noreferrer';el.append(a)}root.append(el)})}
function renderContests(){const r=$('contestList'),items=data.contests.filter(x=>x.published===true);if(renderEmpty(r,items,'Er is nog geen winactie geopend.'))return;items.forEach(x=>{const el=n('div',undefined,'mini-card');panelHead(el,x.title||'Winactie',x.description||'');if(x.end)el.append(n('p',`Sluit: ${dateStr(x.end)}`,'muted small'));let field=n('input');field.maxLength=300;field.placeholder='Jouw antwoord of motivatie';field.setAttribute('aria-label','Winactie-antwoord');let b=n('button','Doe mee','small-btn');b.disabled=Boolean(x.end&&new Date(x.end)<new Date());b.addEventListener('click',async()=>{if(!needsLogin())return;try{const ans=field.value.trim();if(!ans)return notice('contestMsg','Vul eerst je antwoord in.');if(ans.length>300)return;await fb.setDoc(fb.doc(db,'entries',x.id+'_'+user.uid),{contestId:x.id,uid:user.uid,answer:ans,createdAt:fb.serverTimestamp()});notice('contestMsg','Je inzending is ontvangen. Veel succes!')}catch(e){notice('contestMsg',`Meedoen niet gelukt: ${friendly(e)}`)}});el.append(field,b);r.append(el)})}
function renderPolls(){let r=$('pollList'),items=data.polls.filter(x=>x.published===true);if(renderEmpty(r,items,'Er staan nog geen stemrondes open.'))return;items.forEach(p=>{let e=n('div',undefined,'mini-card');panelHead(e,p.question||'Stem mee',p.description||'');if(Array.isArray(p.options)){p.options.slice(0,8).forEach((option,i)=>{const b=n('button',option,'poll-option');b.addEventListener('click',async()=>{if(!needsLogin())return;try{await fb.setDoc(fb.doc(db,'polls',p.id,'votes',user.uid),{uid:user.uid,choice:i,createdAt:fb.serverTimestamp()});alert('Je stem is opgeslagen.') }catch(e){alert('Stemmen niet gelukt. Je kunt per poll één keer stemmen. '+friendly(e))}});e.append(b)})}r.append(e)})}
const renderers={news:renderNews,top40:renderTop,djs:renderDjs,programs:renderSchedule,station:renderSchedule,events:renderEvents,contests:renderContests,polls:renderPolls};
function friendly(err){const s=String(err?.code||'');if(s.includes('permission-denied'))return 'Geen toestemming of al ingezonden.';if(s.includes('network'))return 'Controleer je internetverbinding.';if(s.includes('auth/'))return 'Controleer je inloggegevens.';return 'Probeer het later opnieuw.'}
function showAuth(msg=''){const d=$('authDialog');d.hidden=false;notice('authMsg',msg);$('authForm').querySelector('input[name=email]').focus()}
$('loginBtn').onclick=()=>user?logout():showAuth();$('authClose').onclick=()=>{$('authDialog').hidden=true};$('authDialog').addEventListener('click',e=>{if(e.target===$('authDialog'))$('authDialog').hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('authDialog').hidden=true});
$('authForm').addEventListener('submit',async e=>{e.preventDefault();if(!fb)return notice('authMsg','Firebase is nog niet aangesloten.');const f=new FormData(e.currentTarget);try{await fb.signInWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')));$('authDialog').hidden=true}catch(er){notice('authMsg','Inloggen mislukt. '+friendly(er))}});
$('registerBtn').onclick=async()=>{if(!fb)return notice('authMsg','Firebase is nog niet aangesloten.');const f=new FormData($('authForm'));if(String(f.get('password')).length<6)return notice('authMsg','Minimaal zes tekens vereist.');try{await fb.createUserWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')));$('authDialog').hidden=true}catch(er){notice('authMsg','Account maken mislukt. '+friendly(er))}};
$('googleBtn').onclick=async()=>{if(!fb)return notice('authMsg','Firebase is nog niet aangesloten.');try{await fb.signInWithPopup(auth,new fb.GoogleAuthProvider());$('authDialog').hidden=true}catch(e){notice('authMsg','Google-inloggen mislukt. '+friendly(e))}};
async function logout(){if(auth)await fb.signOut(auth)}$('logoutBtn').onclick=logout;
$('requestForm').addEventListener('submit',async e=>{e.preventDefault();if(!needsLogin())return;let form=new FormData(e.currentTarget);const artist=String(form.get('artist')).trim(),title=String(form.get('title')).trim(),message=String(form.get('message')).trim();if(!artist||!title)return;let btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await fb.addDoc(fb.collection(db,'requests'),{uid:user.uid,artist,title,message,createdAt:fb.serverTimestamp(),status:'new'});notice('requestMsg','Je verzoek is veilig verzonden naar de redactie.');e.currentTarget.reset()}catch(er){notice('requestMsg',friendly(er))}finally{btn.disabled=false}});
$('chatForm').addEventListener('submit',async e=>{e.preventDefault();if(!needsLogin())return;const input=e.currentTarget.elements.message,msg=input.value.trim();if(!msg||msg.length>250)return;try{await fb.addDoc(fb.collection(db,'chat'),{uid:user.uid,name:(user.displayName||user.email?.split('@')[0]||'Luisteraar').slice(0,36),message:msg,createdAt:fb.serverTimestamp()});input.value='';notice('chatMsg','')}catch(er){notice('chatMsg',friendly(er))}});
function renderChats(items){const r=$('chatMessages');if(renderEmpty(r,items,'Er zijn nog geen berichten. Begin het gesprek!'))return;items.sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)).forEach(x=>{let e=n('div',undefined,'chat-item');e.append(n('b',(x.name||'Luisteraar').slice(0,36)+': '));e.append(document.createTextNode((x.message||'').slice(0,250)));if(admin){let del=n('button','×','icon-delete');del.title='Verwijder chatbericht';del.addEventListener('click',()=>fb.deleteDoc(fb.doc(db,'chat',x.id)));e.append(del)}r.append(e)});r.scrollTop=r.scrollHeight}
const docs = col => fb.query(fb.collection(db,col),fb.limit(80));
async function listenPublic(){for(const c of collectionNames){listenUnsubs.push(fb.onSnapshot(docs(c),s=>{data[c]=s.docs.map(d=>({id:d.id,...d.data()}));renderers[c]?.()},e=>{console.warn('MAX data',c,e);}))}listenUnsubs.push(fb.onSnapshot(fb.query(fb.collection(db,'chat'),fb.orderBy('createdAt','desc'),fb.limit(50)),s=>renderChats(s.docs.map(d=>({id:d.id,...d.data()}))),()=>notice('chatMsg','Chat kon niet worden geladen.')))}
function adminRequests(items,rootId){let root=$(rootId);if(renderEmpty(root,items,'Geen nieuwe items.'))return;items.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).forEach(x=>{const e=n('div',undefined,'mini-card');panelHead(e,rootId==='adminRequests'?`${x.artist} — ${x.title}`:x.contestId,x.answer||x.message||'');e.append(n('p',x.status||x.uid,'muted small'));if(rootId==='adminRequests'){const b=n('button','Markeer verwerkt','small-btn');b.onclick=()=>fb.updateDoc(fb.doc(db,'requests',x.id),{status:'processed'});e.append(b)}root.append(e)})}
async function activateAdmin(){if(!admin)return;$('adminClosed').hidden=true;$('adminPanel').hidden=false;listenUnsubs.push(fb.onSnapshot(docs('requests'),s=>adminRequests(s.docs.map(d=>({id:d.id,...d.data()})),'adminRequests')));listenUnsubs.push(fb.onSnapshot(docs('entries'),s=>adminRequests(s.docs.map(d=>({id:d.id,...d.data()})),'adminEntries')))}
function adminExample(){const types={news:{title:'Nieuwsbericht',body:'Schrijf hier je nieuws',date:new Date().toISOString(),published:false,url:''},top40:{rank:1,artist:'',title:'',published:false},djs:{name:'',bio:'',image:'',published:false},programs:{title:'',day:'Maandag',start:'10:00',end:'12:00',dj:'',sort:1,published:false},events:{title:'',description:'',date:'2026-12-31T20:00:00+01:00',published:false},contests:{title:'',description:'',end:'2026-12-31T20:00:00+01:00',published:false},polls:{question:'',options:['Optie A','Optie B'],published:false},station:{program:'',dj:''}};$('adminJson').value=JSON.stringify(types[$('adminCollection').value],null,2);if($('adminCollection').value==='station')$('adminId').value='current'}
$('adminCollection').addEventListener('change',adminExample);adminExample();
$('adminSave').addEventListener('click',async()=>{if(!admin||!db)return;const col=$('adminCollection').value,id=$('adminId').value.trim();if(!collectionNames.includes(col))return;let obj;try{obj=JSON.parse($('adminJson').value);if(!obj||Array.isArray(obj)||typeof obj!=='object')throw Error()}catch{return notice('adminMessage','Controleer de JSON-inhoud.')};if(col==='station'&&id!=='current')return notice('adminMessage','Gebruik document-ID current voor de huidige uitzending.');try{if(col==='contests'){const end=new Date(obj.end);if(!Number.isFinite(end.getTime()))return notice('adminMessage','Vul bij winacties een geldige einddatum in.');obj.endAt=fb.Timestamp.fromDate(end)}if(id){if(!/^[a-zA-Z0-9_-]{1,90}$/.test(id))return notice('adminMessage','Ongeldig document-ID.');await fb.setDoc(fb.doc(db,col,id),obj)}else{const doc=await fb.addDoc(fb.collection(db,col),obj);$('adminId').value=doc.id}notice('adminMessage','Opgeslagen.') }catch(e){notice('adminMessage',friendly(e))}});
$('adminRemove').addEventListener('click',async()=>{if(!admin||!db)return;const id=$('adminId').value.trim(),col=$('adminCollection').value;if(!id||col==='station')return notice('adminMessage','Kies een document-ID.');if(!confirm('Dit gepubliceerde onderdeel echt verwijderen?'))return;try{await fb.deleteDoc(fb.doc(db,col,id));notice('adminMessage','Verwijderd.')}catch(e){notice('adminMessage',friendly(e))}});
$('notifyBtn').onclick=async()=>{if(!fb||!CFG.vapidKey)return notice('notifyStatus','Pushmeldingen worden geactiveerd zodra de beheerder Firebase Cloud Messaging en de VAPID-sleutel instelt.');if(!needsLogin())return;if(!('Notification' in window)||!('serviceWorker' in navigator))return notice('notifyStatus','Deze browser ondersteunt geen webpush.');try{const perm=await Notification.requestPermission();if(perm!=='granted')return notice('notifyStatus','Geen toestemming voor meldingen.');const sw=await navigator.serviceWorker.register('./firebase-messaging-sw.js',{scope:'./push/'});const token=await fb.getToken(messaging,{vapidKey:CFG.vapidKey,serviceWorkerRegistration:sw});if(!token)return notice('notifyStatus','Er kon geen token worden opgehaald.');await fb.setDoc(fb.doc(db,'pushSubscriptions',user.uid),{uid:user.uid,token,updatedAt:fb.serverTimestamp()});notice('notifyStatus','Meldingen op dit apparaat zijn ingeschakeld.')}catch(e){notice('notifyStatus','Meldingen instellen niet gelukt. Controleer Firebase Messaging.')}};
$('pushSend').onclick=async()=>{if(!admin||!fn)return;try{const send=fb.httpsCallable(fn,'announceEvent');const r=await send({title:'MAX HITRADIO',body:'Een speciale uitzending komt eraan!',url:'https://thegamerscube.nl/max/#events'});notice('adminMessage',`Melding aangeboden: ${r.data?.sent||0} tokens`)}catch(e){notice('adminMessage','Pushbericht niet verzonden. Controleer de gedeployde Cloud Function en de permissies.')}};
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(CFG.firebase?.apiKey&&CFG.firebase?.projectId){initFirebase()}else{notice('authStatus','De website draait. Communityfuncties worden beschikbaar zodra Firebase is ingesteld.');$('notifyStatus').textContent='Webpush is nog niet aangesloten.'}
async function initFirebase(){try{const [a,b,m,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-functions.js')]);const app=a.initializeApp(CFG.firebase);auth=b.getAuth(app);db=m.getFirestore(app);fn=f.getFunctions(app,CFG.cloudFunctionRegion||'europe-west1');fb={...b,...m,...f};if(CFG.vapidKey){try{const z=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging.js');messaging=z.getMessaging(app);fb={...fb,...z}}catch{}}await listenPublic();b.onAuthStateChanged(auth,async u=>{user=u;admin=false;$('loginBtn').textContent=u?'UITLOGGEN':'INLOGGEN';$('logoutBtn').hidden=!u;listenUnsubs.filter(x=>x._private).forEach(x=>x());if(!u){$('adminPanel').hidden=true;$('adminClosed').hidden=false;notice('authStatus','Log in als beheerder om de MAX Content Studio te openen.');return}try{const r=await m.getDoc(m.doc(db,'roles',u.uid));admin=r.exists()&&r.data().role==='admin'}catch{}notice('authStatus',admin?'Beheerder aangemeld.':'Je bent aangemeld als luisteraar.');if(admin)activateAdmin();try{const r=await m.getDoc(m.doc(db,'favorites',u.uid));if(r.exists()&&Array.isArray(r.data().items)){const old=favorites;favorites=[...r.data().items,...old].filter((t,i,a)=>a.findIndex(x=>x.artist===t.artist&&x.title===t.title)===i).slice(0,80);saveLocal('max-favorites',favorites);renderFav()}}catch{}})}catch(e){console.warn('Firebase setup error',e);notice('authStatus','Firebase-instellingen controleren: community niet verbonden.')}}
